data: "camelyon17"
backbone: "densenet121"
pretrained: true
augmentation: true
randaugment: false
optimizer: "sgd"
learning_rate: 0.03
weight_decay: 0.000001
lr_scheduler: "cosine_decay"
train_domains:
- 0
- 3
- 4
validation_domains:
- 1
test_domains:
- 2
max_epochs: 5
batch_size: 32
num_workers: 4
pin_memory: true
prefetch_factor: true
persistent_workers: false