data: camelyon17
train_domains:
- 0
- 3
- 4
validation_domains:
- 1
test_domains:
- 2
backbone: densenet121
imagenet: true
augmentation: true
randaugment: false
optimizer: adam
learning_rate: 0.00001
weight_decay: 0.000001
lr_scheduler: none
max_epochs: 100
batch_size: 256
num_workers: 16
prefetch_factor: 8