data: poverty
backbone: resnet18
train_domains:
- angola
- benin
- burkina_faso 
- cote_d_ivoire
- ethiopia
- guinea 
- kenya
- lesotho
- mali
- rwanda 
- senegal
- sierra_leone
- tanzania 
- zambia
validation_domains:
- democratic_republic_of_congo
- mozambique
- nigeria
- togo
- uganda
test_domains:
- cameroon
- ghana
- malawi
- zimbabwe
backbone: resnet18
imagenet: true
augmentation: true
randaugment: false
optimizer: adam
learning_rate: 0.0001
weight_decay: 0.00001
lr_scheduler: none
max_epochs: 100
batch_size: 64
num_workers: 16
prefetch_factor: 8