data: poverty
backbone: resnet18
train_domains:
- angola
- cote_d_ivoire
- democratic_republic_of_congo
- ethiopia
- kenya
- lesotho
- mali
- mozambique
- nigeria
- rwanda
- senegal
- togo
- uganda
- zambia
validation_domains:
- cameroon
- ghana
- malawi
- zimbabwe
test_domains:
- benin
- burkina_faso
- guinea
- sierra_leone
- tanzania
backbone: resnet18
imagenet: true
augmentation: true
randaugment: false
optimizer: adam
learning_rate: 0.0001
weight_decay: 0.00001
lr_scheduler: none
max_epochs: 100
batch_size: 64
num_workers: 16
prefetch_factor: 8