data: poverty
backbone: resnet18
train_domains:
- angola
- benin
- burkina_faso
- cameroon
- cote_d_ivoire
- ethiopia
- ghana
- guinea
- malawi
- mali
- rwanda
- sierra_leone
- tanzania
- zimbabwe
validation_domains:
- kenya
- lesotho 
- senegal
- zambia
test_domains:
- democratic_republic_of_congo
- mozambique
- nigeria
- togo
- uganda
backbone: resnet18
imagenet: true
augmentation: true
randaugment: false
g_optimizer: adamw
g_learning_rate: 0.0001
g_weight_decay: 0.00001
g_lr_scheduler: none
pretrained_g_ckpt: none
freeze_g_encoder: false
freeze_g_predictor: false
f_optimizer: sgd
f_learning_rate: 0.001
f_weight_decay: 0.00001
f_lr_scheduler: cosine_decay
c_optimizer: adam
c_learning_rate: 0.01
c_lr_scheduler: none
batch_size: 64
num_workers: 16
prefetch_factor: 8
max_epochs: 30
early_stopping: 10
monitor_metric: pearson